#!/bin/sh
secret=~/.user
backup=~/.backup

if [ -e "$backup" ] 
then
    echo "$backup exists"
else
    if [ mkdir "$backup" ] 2> /dev/null
    then 
        echo "made backup dir"
    fi
fi

# copy over bashrc
sudo cp /etc/bash.bashrc $backup/bash.bashrc

# make sure
if [ $? -eq 0 ]; then
    echo "Backup ready"
else
    echo "Backup could not be made. Exiting"
    exit 1
fi


# directory for all the magic
if [ -e "$secret" ] 
then
    echo "dir exists"
else
    mkdir "$secret" 
    if [ $? -eq 0 ]
    then 
        echo "made secret dir"
    fi
fi

# Making the required files
cd programs/
for file in *
do
    chmod +x "$file"

    echo "copying $file to $secret"
    cp ./"$file" "$secret"/"$file"
done

# Add folder to path
echo "PATH=$secret:$PATH" >> /etc/bash.bashrc

