#!/bin/sh

secret="$HOME/.user"
backup="$HOME/.backup"

if [ -e "$backup" ] 
then
    echo "$backup exists"
else
    mkdir "$backup" && echo "made backup dir"
fi

# copy over bashrc
sudo cp /etc/bash.bashrc "$backup/bash.bashrc"

# make sure
if [ $? -eq 0 ]; then
    echo "Backup ready"
else
    echo "Backup could not be made. Exiting"
    exit 1
fi

# directory for all the magic
if [ -e "$secret" ] 
then
    echo "dir exists"
else
    mkdir "$secret" 
    if [ $? -eq 0 ]
    then 
        echo "made secret dir"
    fi
fi

# Making the required files
cd programs/
for file in *
do
    chmod +x "$file"

    echo "copying $file to $secret"
    cp ./"$file" "$secret"/"$file"
done

# finding the user
user="`whoami`"
sudo chown -R "$user" "$secret"

# Add folder to path
if [ -z "`echo $PATH | grep "$secret"`" ]; then
    echo "export PATH=\"$secret:$PATH\"" | sudo tee -a /etc/bash.bashrc > /dev/null
else
    if [ -z "`sudo grep "$secret" /etc/bash.bashrc`" ]; then
        echo "export PATH=\"$PATH\"" | sudo tee -a /etc/bash.bashrc > /dev/null
    fi
fi

echo "Done. Open new shell to complete setup"

