#!/bin/sh

#echo "hijacked"
export PATH=`echo $PATH | sed -e s/^[^:]*://`

#echo "still here"
if [ "$#" -ne 0 ]; 
then
	color=$1;
	shift;
fi

if [ -z "$@" ]
then
	# Single lined ls
	# echo "single lined"

	ls $color
else
	echo "not.";
	if echo "$@" | grep "\-[^ ]*l";
	then
		echo "Aight"
		ls $@ --color | grep --color -v ".user" | grep -v ".backup"
	else
		ls $@ --color | sed -z "s/ ?.user//"
	fi
	#echo "${array[@]}" =~ "-.*l"
fi

export PATH=~/.user/$PATH